# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateDataSource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CreateDataSource.proto',
  package='qlua.rpc.datasource.CreateDataSource',
  syntax='proto3',
  serialized_options=_b('\n\023qlua.rpc.datasourceH\001'),
  serialized_pb=_b('\n\x16\x43reateDataSource.proto\x12$qlua.rpc.datasource.CreateDataSource\"\x80\x01\n\x07Request\x12\x12\n\nclass_code\x18\x01 \x01(\t\x12\x10\n\x08sec_code\x18\x02 \x01(\t\x12@\n\x08interval\x18\x03 \x01(\x0e\x32..qlua.rpc.datasource.CreateDataSource.Interval\x12\r\n\x05param\x18\x04 \x01(\t\"G\n\x06Result\x12\x17\n\x0f\x64\x61tasource_uuid\x18\x01 \x01(\t\x12\x10\n\x08is_error\x18\x02 \x01(\x08\x12\x12\n\nerror_desc\x18\x03 \x01(\t*\xc1\x02\n\x08Interval\x12\r\n\tUNDEFINED\x10\x00\x12\x11\n\rINTERVAL_TICK\x10\x01\x12\x0f\n\x0bINTERVAL_M1\x10\x02\x12\x0f\n\x0bINTERVAL_M2\x10\x03\x12\x0f\n\x0bINTERVAL_M3\x10\x04\x12\x0f\n\x0bINTERVAL_M4\x10\x05\x12\x0f\n\x0bINTERVAL_M5\x10\x06\x12\x0f\n\x0bINTERVAL_M6\x10\x07\x12\x10\n\x0cINTERVAL_M10\x10\x08\x12\x10\n\x0cINTERVAL_M15\x10\t\x12\x10\n\x0cINTERVAL_M20\x10\n\x12\x10\n\x0cINTERVAL_M30\x10\x0b\x12\x0f\n\x0bINTERVAL_H1\x10\x0c\x12\x0f\n\x0bINTERVAL_H2\x10\r\x12\x0f\n\x0bINTERVAL_H4\x10\x0e\x12\x0f\n\x0bINTERVAL_D1\x10\x0f\x12\x0f\n\x0bINTERVAL_W1\x10\x10\x12\x10\n\x0cINTERVAL_MN1\x10\x11\x42\x17\n\x13qlua.rpc.datasourceH\x01\x62\x06proto3')
)

_INTERVAL = _descriptor.EnumDescriptor(
  name='Interval',
  full_name='qlua.rpc.datasource.CreateDataSource.Interval',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_TICK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M1', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M2', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M3', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M4', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M5', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M6', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M10', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M15', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M20', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_M30', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_H1', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_H2', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_H4', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_D1', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_W1', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_MN1', index=17, number=17,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=269,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_INTERVAL)

Interval = enum_type_wrapper.EnumTypeWrapper(_INTERVAL)
UNDEFINED = 0
INTERVAL_TICK = 1
INTERVAL_M1 = 2
INTERVAL_M2 = 3
INTERVAL_M3 = 4
INTERVAL_M4 = 5
INTERVAL_M5 = 6
INTERVAL_M6 = 7
INTERVAL_M10 = 8
INTERVAL_M15 = 9
INTERVAL_M20 = 10
INTERVAL_M30 = 11
INTERVAL_H1 = 12
INTERVAL_H2 = 13
INTERVAL_H4 = 14
INTERVAL_D1 = 15
INTERVAL_W1 = 16
INTERVAL_MN1 = 17



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.datasource.CreateDataSource.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_code', full_name='qlua.rpc.datasource.CreateDataSource.Request.class_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sec_code', full_name='qlua.rpc.datasource.CreateDataSource.Request.sec_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='qlua.rpc.datasource.CreateDataSource.Request.interval', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='qlua.rpc.datasource.CreateDataSource.Request.param', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=193,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.datasource.CreateDataSource.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasource_uuid', full_name='qlua.rpc.datasource.CreateDataSource.Result.datasource_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_error', full_name='qlua.rpc.datasource.CreateDataSource.Result.is_error', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_desc', full_name='qlua.rpc.datasource.CreateDataSource.Result.error_desc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=266,
)

_REQUEST.fields_by_name['interval'].enum_type = _INTERVAL
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['Interval'] = _INTERVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'CreateDataSource_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.datasource.CreateDataSource.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'CreateDataSource_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.datasource.CreateDataSource.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
