# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getBuySellInfoEx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qlua.rpc import getBuySellInfo_pb2 as qlua_dot_rpc_dot_getBuySellInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='getBuySellInfoEx.proto',
  package='qlua.rpc.getBuySellInfoEx',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x16getBuySellInfoEx.proto\x12\x19qlua.rpc.getBuySellInfoEx\x1a\x1dqlua/rpc/getBuySellInfo.proto\"\xf2\x01\n\rBuySellInfoEx\x12;\n\rbuy_sell_info\x18\x01 \x01(\x0b\x32$.qlua.rpc.getBuySellInfo.BuySellInfo\x12\x12\n\nlimit_kind\x18\x02 \x01(\t\x12\x0e\n\x06\x64_long\x18\x03 \x01(\t\x12\x12\n\nd_min_long\x18\x04 \x01(\t\x12\x0f\n\x07\x64_short\x18\x05 \x01(\t\x12\x13\n\x0b\x64_min_short\x18\x06 \x01(\t\x12\x13\n\x0b\x63lient_type\x18\x07 \x01(\t\x12\x17\n\x0fis_long_allowed\x18\x08 \x01(\t\x12\x18\n\x10is_short_allowed\x18\t \x01(\t\"d\n\x07Request\x12\x0f\n\x07\x66irm_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_code\x18\x02 \x01(\t\x12\x12\n\nclass_code\x18\x03 \x01(\t\x12\x10\n\x08sec_code\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\t\"L\n\x06Result\x12\x42\n\x10\x62uy_sell_info_ex\x18\x01 \x01(\x0b\x32(.qlua.rpc.getBuySellInfoEx.BuySellInfoExB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
  ,
  dependencies=[qlua_dot_rpc_dot_getBuySellInfo__pb2.DESCRIPTOR,])




_BUYSELLINFOEX = _descriptor.Descriptor(
  name='BuySellInfoEx',
  full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy_sell_info', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.buy_sell_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_kind', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.limit_kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d_long', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.d_long', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d_min_long', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.d_min_long', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d_short', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.d_short', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d_min_short', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.d_min_short', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_type', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.client_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_long_allowed', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.is_long_allowed', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_short_allowed', full_name='qlua.rpc.getBuySellInfoEx.BuySellInfoEx.is_short_allowed', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=327,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.getBuySellInfoEx.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firm_id', full_name='qlua.rpc.getBuySellInfoEx.Request.firm_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_code', full_name='qlua.rpc.getBuySellInfoEx.Request.client_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_code', full_name='qlua.rpc.getBuySellInfoEx.Request.class_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sec_code', full_name='qlua.rpc.getBuySellInfoEx.Request.sec_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='qlua.rpc.getBuySellInfoEx.Request.price', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=429,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.getBuySellInfoEx.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy_sell_info_ex', full_name='qlua.rpc.getBuySellInfoEx.Result.buy_sell_info_ex', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=507,
)

_BUYSELLINFOEX.fields_by_name['buy_sell_info'].message_type = qlua_dot_rpc_dot_getBuySellInfo__pb2._BUYSELLINFO
_RESULT.fields_by_name['buy_sell_info_ex'].message_type = _BUYSELLINFOEX
DESCRIPTOR.message_types_by_name['BuySellInfoEx'] = _BUYSELLINFOEX
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuySellInfoEx = _reflection.GeneratedProtocolMessageType('BuySellInfoEx', (_message.Message,), dict(
  DESCRIPTOR = _BUYSELLINFOEX,
  __module__ = 'getBuySellInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getBuySellInfoEx.BuySellInfoEx)
  ))
_sym_db.RegisterMessage(BuySellInfoEx)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'getBuySellInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getBuySellInfoEx.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'getBuySellInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getBuySellInfoEx.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
