# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getPortfolioInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='getPortfolioInfo.proto',
  package='qlua.rpc.getPortfolioInfo',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x16getPortfolioInfo.proto\x12\x19qlua.rpc.getPortfolioInfo\"\xea\x06\n\rPortfolioInfo\x12\x13\n\x0bis_leverage\x18\x01 \x01(\t\x12\x11\n\tin_assets\x18\x02 \x01(\t\x12\x10\n\x08leverage\x18\x03 \x01(\t\x12\x12\n\nopen_limit\x18\x04 \x01(\t\x12\x11\n\tval_short\x18\x05 \x01(\t\x12\x10\n\x08val_long\x18\x06 \x01(\t\x12\x17\n\x0fval_long_margin\x18\x07 \x01(\t\x12\x16\n\x0eval_long_asset\x18\x08 \x01(\t\x12\x0e\n\x06\x61ssets\x18\t \x01(\t\x12\x14\n\x0c\x63ur_leverage\x18\n \x01(\t\x12\x0e\n\x06margin\x18\x0b \x01(\t\x12\x0f\n\x07lim_all\x18\x0c \x01(\t\x12\x12\n\nav_lim_all\x18\r \x01(\t\x12\x12\n\nlocked_buy\x18\x0e \x01(\t\x12\x19\n\x11locked_buy_margin\x18\x0f \x01(\t\x12\x18\n\x10locked_buy_asset\x18\x10 \x01(\t\x12\x13\n\x0blocked_sell\x18\x11 \x01(\t\x12\x19\n\x11locked_value_coef\x18\x12 \x01(\t\x12\x15\n\rin_all_assets\x18\x13 \x01(\t\x12\x12\n\nall_assets\x18\x14 \x01(\t\x12\x13\n\x0bprofit_loss\x18\x15 \x01(\t\x12\x13\n\x0brate_change\x18\x16 \x01(\t\x12\x0f\n\x07lim_buy\x18\x17 \x01(\t\x12\x10\n\x08lim_sell\x18\x18 \x01(\t\x12\x16\n\x0elim_non_margin\x18\x19 \x01(\t\x12\x15\n\rlim_buy_asset\x18\x1a \x01(\t\x12\x15\n\rval_short_net\x18\x1b \x01(\t\x12\x14\n\x0cval_long_net\x18\x1c \x01(\t\x12\x17\n\x0ftotal_money_bal\x18\x1d \x01(\t\x12\x1a\n\x12total_locked_money\x18\x1e \x01(\t\x12\x10\n\x08haircuts\x18\x1f \x01(\t\x12\x19\n\x11\x61ssets_without_hc\x18  \x01(\t\x12\x13\n\x0bstatus_coef\x18! \x01(\t\x12\x11\n\tvarmargin\x18\" \x01(\t\x12\x18\n\x10go_for_positions\x18# \x01(\t\x12\x15\n\rgo_for_orders\x18$ \x01(\t\x12\x14\n\x0crate_futures\x18% \x01(\t\x12\x16\n\x0eis_qual_client\x18& \x01(\t\x12\x12\n\nis_futures\x18\' \x01(\t\x12\x10\n\x08\x63urr_tag\x18( \x01(\t\"/\n\x07Request\x12\x0f\n\x07\x66irm_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_code\x18\x02 \x01(\t\"J\n\x06Result\x12@\n\x0eportfolio_info\x18\x01 \x01(\x0b\x32(.qlua.rpc.getPortfolioInfo.PortfolioInfoB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
)




_PORTFOLIOINFO = _descriptor.Descriptor(
  name='PortfolioInfo',
  full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_leverage', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.is_leverage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_assets', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.in_assets', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leverage', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.leverage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_limit', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.open_limit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_short', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_short', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_long', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_long', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_long_margin', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_long_margin', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_long_asset', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_long_asset', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assets', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.assets', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cur_leverage', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.cur_leverage', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='margin', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.margin', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lim_all', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.lim_all', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='av_lim_all', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.av_lim_all', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_buy', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.locked_buy', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_buy_margin', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.locked_buy_margin', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_buy_asset', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.locked_buy_asset', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_sell', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.locked_sell', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_value_coef', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.locked_value_coef', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_all_assets', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.in_all_assets', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_assets', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.all_assets', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profit_loss', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.profit_loss', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate_change', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.rate_change', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lim_buy', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.lim_buy', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lim_sell', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.lim_sell', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lim_non_margin', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.lim_non_margin', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lim_buy_asset', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.lim_buy_asset', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_short_net', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_short_net', index=26,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_long_net', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.val_long_net', index=27,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_money_bal', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.total_money_bal', index=28,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_locked_money', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.total_locked_money', index=29,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='haircuts', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.haircuts', index=30,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assets_without_hc', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.assets_without_hc', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_coef', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.status_coef', index=32,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='varmargin', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.varmargin', index=33,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='go_for_positions', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.go_for_positions', index=34,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='go_for_orders', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.go_for_orders', index=35,
      number=36, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate_futures', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.rate_futures', index=36,
      number=37, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_qual_client', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.is_qual_client', index=37,
      number=38, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_futures', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.is_futures', index=38,
      number=39, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curr_tag', full_name='qlua.rpc.getPortfolioInfo.PortfolioInfo.curr_tag', index=39,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=928,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.getPortfolioInfo.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firm_id', full_name='qlua.rpc.getPortfolioInfo.Request.firm_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_code', full_name='qlua.rpc.getPortfolioInfo.Request.client_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=930,
  serialized_end=977,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.getPortfolioInfo.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='portfolio_info', full_name='qlua.rpc.getPortfolioInfo.Result.portfolio_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=979,
  serialized_end=1053,
)

_RESULT.fields_by_name['portfolio_info'].message_type = _PORTFOLIOINFO
DESCRIPTOR.message_types_by_name['PortfolioInfo'] = _PORTFOLIOINFO
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortfolioInfo = _reflection.GeneratedProtocolMessageType('PortfolioInfo', (_message.Message,), dict(
  DESCRIPTOR = _PORTFOLIOINFO,
  __module__ = 'getPortfolioInfo_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfo.PortfolioInfo)
  ))
_sym_db.RegisterMessage(PortfolioInfo)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'getPortfolioInfo_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfo.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'getPortfolioInfo_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfo.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
