# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getPortfolioInfoEx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qlua.rpc import getPortfolioInfo_pb2 as qlua_dot_rpc_dot_getPortfolioInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='getPortfolioInfoEx.proto',
  package='qlua.rpc.getPortfolioInfoEx',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x18getPortfolioInfoEx.proto\x12\x1bqlua.rpc.getPortfolioInfoEx\x1a\x1fqlua/rpc/getPortfolioInfo.proto\"\xe6\x04\n\x0fPortfolioInfoEx\x12@\n\x0eportfolio_info\x18\x01 \x01(\x0b\x32(.qlua.rpc.getPortfolioInfo.PortfolioInfo\x12\x13\n\x0binit_margin\x18\x02 \x01(\t\x12\x12\n\nmin_margin\x18\x03 \x01(\t\x12\x18\n\x10\x63orrected_margin\x18\x04 \x01(\t\x12\x13\n\x0b\x63lient_type\x18\x05 \x01(\t\x12\x17\n\x0fportfolio_value\x18\x06 \x01(\t\x12\x1c\n\x14start_limit_open_pos\x18\x07 \x01(\t\x12\x1c\n\x14total_limit_open_pos\x18\x08 \x01(\t\x12\x16\n\x0elimit_open_pos\x18\t \x01(\t\x12\x19\n\x11used_lim_open_pos\x18\n \x01(\t\x12\x16\n\x0e\x61\x63\x63_var_margin\x18\x0b \x01(\t\x12\x15\n\rcl_var_margin\x18\x0c \x01(\t\x12\x17\n\x0fopt_liquid_cost\x18\r \x01(\t\x12\x11\n\tfut_asset\x18\x0e \x01(\t\x12\x17\n\x0f\x66ut_total_asset\x18\x0f \x01(\t\x12\x10\n\x08\x66ut_debt\x18\x10 \x01(\t\x12\x16\n\x0e\x66ut_rate_asset\x18\x11 \x01(\t\x12\x1b\n\x13\x66ut_rate_asset_open\x18\x12 \x01(\t\x12\x13\n\x0b\x66ut_rate_go\x18\x13 \x01(\t\x12\x16\n\x0eplaned_rate_go\x18\x14 \x01(\t\x12\x15\n\rcash_leverage\x18\x15 \x01(\t\x12\x19\n\x11\x66ut_position_type\x18\x16 \x01(\t\x12\x17\n\x0f\x66ut_accured_int\x18\x17 \x01(\t\"C\n\x07Request\x12\x0f\n\x07\x66irm_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_code\x18\x02 \x01(\t\x12\x12\n\nlimit_kind\x18\x03 \x01(\x05\"Q\n\x06Result\x12G\n\x11portfolio_info_ex\x18\x01 \x01(\x0b\x32,.qlua.rpc.getPortfolioInfoEx.PortfolioInfoExB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
  ,
  dependencies=[qlua_dot_rpc_dot_getPortfolioInfo__pb2.DESCRIPTOR,])




_PORTFOLIOINFOEX = _descriptor.Descriptor(
  name='PortfolioInfoEx',
  full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='portfolio_info', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.portfolio_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_margin', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.init_margin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_margin', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.min_margin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corrected_margin', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.corrected_margin', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_type', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.client_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portfolio_value', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.portfolio_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_limit_open_pos', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.start_limit_open_pos', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_limit_open_pos', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.total_limit_open_pos', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_open_pos', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.limit_open_pos', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='used_lim_open_pos', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.used_lim_open_pos', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_var_margin', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.acc_var_margin', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cl_var_margin', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.cl_var_margin', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt_liquid_cost', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.opt_liquid_cost', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_asset', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_asset', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_total_asset', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_total_asset', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_debt', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_debt', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_rate_asset', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_asset', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_rate_asset_open', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_asset_open', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_rate_go', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_go', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='planed_rate_go', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.planed_rate_go', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cash_leverage', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.cash_leverage', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_position_type', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_position_type', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fut_accured_int', full_name='qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_accured_int', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=705,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.getPortfolioInfoEx.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firm_id', full_name='qlua.rpc.getPortfolioInfoEx.Request.firm_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_code', full_name='qlua.rpc.getPortfolioInfoEx.Request.client_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_kind', full_name='qlua.rpc.getPortfolioInfoEx.Request.limit_kind', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=774,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.getPortfolioInfoEx.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='portfolio_info_ex', full_name='qlua.rpc.getPortfolioInfoEx.Result.portfolio_info_ex', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=857,
)

_PORTFOLIOINFOEX.fields_by_name['portfolio_info'].message_type = qlua_dot_rpc_dot_getPortfolioInfo__pb2._PORTFOLIOINFO
_RESULT.fields_by_name['portfolio_info_ex'].message_type = _PORTFOLIOINFOEX
DESCRIPTOR.message_types_by_name['PortfolioInfoEx'] = _PORTFOLIOINFOEX
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortfolioInfoEx = _reflection.GeneratedProtocolMessageType('PortfolioInfoEx', (_message.Message,), dict(
  DESCRIPTOR = _PORTFOLIOINFOEX,
  __module__ = 'getPortfolioInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx)
  ))
_sym_db.RegisterMessage(PortfolioInfoEx)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'getPortfolioInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfoEx.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'getPortfolioInfoEx_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getPortfolioInfoEx.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
