# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getQuoteLevel2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='getQuoteLevel2.proto',
  package='qlua.rpc.getQuoteLevel2',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x14getQuoteLevel2.proto\x12\x17qlua.rpc.getQuoteLevel2\"-\n\nQuoteEntry\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\t\"/\n\x07Request\x12\x12\n\nclass_code\x18\x01 \x01(\t\x12\x10\n\x08sec_code\x18\x02 \x01(\t\"\x98\x01\n\x06Result\x12\x11\n\tbid_count\x18\x01 \x01(\t\x12\x13\n\x0boffer_count\x18\x02 \x01(\t\x12\x31\n\x04\x62ids\x18\x03 \x03(\x0b\x32#.qlua.rpc.getQuoteLevel2.QuoteEntry\x12\x33\n\x06offers\x18\x04 \x03(\x0b\x32#.qlua.rpc.getQuoteLevel2.QuoteEntryB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
)




_QUOTEENTRY = _descriptor.Descriptor(
  name='QuoteEntry',
  full_name='qlua.rpc.getQuoteLevel2.QuoteEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='qlua.rpc.getQuoteLevel2.QuoteEntry.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='qlua.rpc.getQuoteLevel2.QuoteEntry.quantity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=94,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.getQuoteLevel2.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_code', full_name='qlua.rpc.getQuoteLevel2.Request.class_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sec_code', full_name='qlua.rpc.getQuoteLevel2.Request.sec_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=143,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.getQuoteLevel2.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bid_count', full_name='qlua.rpc.getQuoteLevel2.Result.bid_count', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer_count', full_name='qlua.rpc.getQuoteLevel2.Result.offer_count', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bids', full_name='qlua.rpc.getQuoteLevel2.Result.bids', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offers', full_name='qlua.rpc.getQuoteLevel2.Result.offers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=298,
)

_RESULT.fields_by_name['bids'].message_type = _QUOTEENTRY
_RESULT.fields_by_name['offers'].message_type = _QUOTEENTRY
DESCRIPTOR.message_types_by_name['QuoteEntry'] = _QUOTEENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuoteEntry = _reflection.GeneratedProtocolMessageType('QuoteEntry', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEENTRY,
  __module__ = 'getQuoteLevel2_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getQuoteLevel2.QuoteEntry)
  ))
_sym_db.RegisterMessage(QuoteEntry)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'getQuoteLevel2_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getQuoteLevel2.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'getQuoteLevel2_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getQuoteLevel2.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
