# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getSecurityInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qlua.rpc import qlua_structures_pb2 as qlua_dot_rpc_dot_qlua__structures__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='getSecurityInfo.proto',
  package='qlua.rpc.getSecurityInfo',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x15getSecurityInfo.proto\x12\x18qlua.rpc.getSecurityInfo\x1a\x1eqlua/rpc/qlua_structures.proto\"/\n\x07Request\x12\x12\n\nclass_code\x18\x01 \x01(\t\x12\x10\n\x08sec_code\x18\x02 \x01(\t\"7\n\x06Result\x12-\n\rsecurity_info\x18\x01 \x01(\x0b\x32\x16.qlua.structs.SecurityB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
  ,
  dependencies=[qlua_dot_rpc_dot_qlua__structures__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.getSecurityInfo.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_code', full_name='qlua.rpc.getSecurityInfo.Request.class_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sec_code', full_name='qlua.rpc.getSecurityInfo.Request.sec_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=130,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.getSecurityInfo.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='security_info', full_name='qlua.rpc.getSecurityInfo.Result.security_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=187,
)

_RESULT.fields_by_name['security_info'].message_type = qlua_dot_rpc_dot_qlua__structures__pb2._SECURITY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'getSecurityInfo_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getSecurityInfo.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'getSecurityInfo_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.getSecurityInfo.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
