# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qlua_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qlua_events.proto',
  package='qlua.events',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11qlua_events.proto\x12\x0bqlua.events*\x9d\x04\n\tEventType\x12\x16\n\x12\x45VENT_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10PUBLISHER_ONLINE\x10\x01\x12\x15\n\x11PUBLISHER_OFFLINE\x10\x02\x12\x0c\n\x08ON_CLOSE\x10\x03\x12\x10\n\x0cON_CONNECTED\x10\x04\x12\x13\n\x0fON_DISCONNECTED\x10\x05\x12\x0b\n\x07ON_FIRM\x10\x06\x12\x10\n\x0cON_ALL_TRADE\x10\x07\x12\x0c\n\x08ON_TRADE\x10\x08\x12\x0c\n\x08ON_ORDER\x10\t\x12\x16\n\x12ON_ACCOUNT_BALANCE\x10\n\x12\x1b\n\x17ON_FUTURES_LIMIT_CHANGE\x10\x0b\x12\x1b\n\x17ON_FUTURES_LIMIT_DELETE\x10\x0c\x12\x1d\n\x19ON_FUTURES_CLIENT_HOLDING\x10\r\x12\x12\n\x0eON_MONEY_LIMIT\x10\x0e\x12\x19\n\x15ON_MONEY_LIMIT_DELETE\x10\x0f\x12\x11\n\rON_DEPO_LIMIT\x10\x10\x12\x18\n\x14ON_DEPO_LIMIT_DELETE\x10\x11\x12\x17\n\x13ON_ACCOUNT_POSITION\x10\x12\x12\x0f\n\x0bON_NEG_DEAL\x10\x13\x12\x10\n\x0cON_NEG_TRADE\x10\x14\x12\x11\n\rON_STOP_ORDER\x10\x15\x12\x12\n\x0eON_TRANS_REPLY\x10\x16\x12\x0c\n\x08ON_PARAM\x10\x17\x12\x0c\n\x08ON_QUOTE\x10\x18\x12\x0f\n\x0bON_CLEAN_UP\x10\x19\x62\x06proto3')
)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='qlua.events.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENT_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLISHER_ONLINE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLISHER_OFFLINE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_CLOSE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_CONNECTED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_DISCONNECTED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_FIRM', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_ALL_TRADE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_TRADE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_ORDER', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_ACCOUNT_BALANCE', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_FUTURES_LIMIT_CHANGE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_FUTURES_LIMIT_DELETE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_FUTURES_CLIENT_HOLDING', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_MONEY_LIMIT', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_MONEY_LIMIT_DELETE', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_DEPO_LIMIT', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_DEPO_LIMIT_DELETE', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_ACCOUNT_POSITION', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_NEG_DEAL', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_NEG_TRADE', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_STOP_ORDER', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_TRANS_REPLY', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_PARAM', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_QUOTE', index=24, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_CLEAN_UP', index=25, number=25,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=35,
  serialized_end=576,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
EVENT_TYPE_UNKNOWN = 0
PUBLISHER_ONLINE = 1
PUBLISHER_OFFLINE = 2
ON_CLOSE = 3
ON_CONNECTED = 4
ON_DISCONNECTED = 5
ON_FIRM = 6
ON_ALL_TRADE = 7
ON_TRADE = 8
ON_ORDER = 9
ON_ACCOUNT_BALANCE = 10
ON_FUTURES_LIMIT_CHANGE = 11
ON_FUTURES_LIMIT_DELETE = 12
ON_FUTURES_CLIENT_HOLDING = 13
ON_MONEY_LIMIT = 14
ON_MONEY_LIMIT_DELETE = 15
ON_DEPO_LIMIT = 16
ON_DEPO_LIMIT_DELETE = 17
ON_ACCOUNT_POSITION = 18
ON_NEG_DEAL = 19
ON_NEG_TRADE = 20
ON_STOP_ORDER = 21
ON_TRANS_REPLY = 22
ON_PARAM = 23
ON_QUOTE = 24
ON_CLEAN_UP = 25


DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
