# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qlua_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qlua_types.proto',
  package='qlua.types',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10qlua_types.proto\x12\nqlua.types\"\"\n\nTableEntry\x12\t\n\x01k\x18\x01 \x01(\t\x12\t\n\x01v\x18\x02 \x01(\tb\x06proto3')
)




_TABLEENTRY = _descriptor.Descriptor(
  name='TableEntry',
  full_name='qlua.types.TableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='qlua.types.TableEntry.k', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='qlua.types.TableEntry.v', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['TableEntry'] = _TABLEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TableEntry = _reflection.GeneratedProtocolMessageType('TableEntry', (_message.Message,), dict(
  DESCRIPTOR = _TABLEENTRY,
  __module__ = 'qlua_types_pb2'
  # @@protoc_insertion_point(class_scope:qlua.types.TableEntry)
  ))
_sym_db.RegisterMessage(TableEntry)


# @@protoc_insertion_point(module_scope)
