# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sendTransaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sendTransaction.proto',
  package='qlua.rpc.sendTransaction',
  syntax='proto3',
  serialized_options=_b('\n\010qlua.rpcH\001'),
  serialized_pb=_b('\n\x15sendTransaction.proto\x12\x18qlua.rpc.sendTransaction\"\x86\x01\n\x07Request\x12G\n\x0btransaction\x18\x01 \x03(\x0b\x32\x32.qlua.rpc.sendTransaction.Request.TransactionEntry\x1a\x32\n\x10TransactionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\tB\x0c\n\x08qlua.rpcH\x01\x62\x06proto3')
)




_REQUEST_TRANSACTIONENTRY = _descriptor.Descriptor(
  name='TransactionEntry',
  full_name='qlua.rpc.sendTransaction.Request.TransactionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='qlua.rpc.sendTransaction.Request.TransactionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='qlua.rpc.sendTransaction.Request.TransactionEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=186,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='qlua.rpc.sendTransaction.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='qlua.rpc.sendTransaction.Request.transaction', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_TRANSACTIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=186,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='qlua.rpc.sendTransaction.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='qlua.rpc.sendTransaction.Result.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=212,
)

_REQUEST_TRANSACTIONENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['transaction'].message_type = _REQUEST_TRANSACTIONENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  TransactionEntry = _reflection.GeneratedProtocolMessageType('TransactionEntry', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_TRANSACTIONENTRY,
    __module__ = 'sendTransaction_pb2'
    # @@protoc_insertion_point(class_scope:qlua.rpc.sendTransaction.Request.TransactionEntry)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'sendTransaction_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.sendTransaction.Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.TransactionEntry)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'sendTransaction_pb2'
  # @@protoc_insertion_point(class_scope:qlua.rpc.sendTransaction.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None
_REQUEST_TRANSACTIONENTRY._options = None
# @@protoc_insertion_point(module_scope)
